name: scheduling_assistant
description: A scheduling assistant app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  fl_chart: ^0.65.0
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.7
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  flutter_file_dialog: ^3.0.2
  flutter_local_notifications: ^15.0.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/sounds/
