name: Flutter CI/CD

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发工作流

# 添加工作流权限
permissions:
  contents: write  # 允许创建Release和上传资源
  issues: write    # 允许创建和更新Issues
  pull-requests: write # 允许创建和更新PR

jobs:
  analyze:
    name: 代码分析
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9 # v4.1.1
        
      - name: 设置Flutter环境
        uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56 # v2.14.0
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true
          
      - name: 缓存Pub依赖
        uses: actions/cache@0769f2e44373d687c841be56f618397100943c5e # v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
          
      - name: 获取依赖
        run: flutter pub get
        
      - name: 自动修复插件问题
        run: |
          FLUTTER_LOCAL_NOTIFICATIONS_PATH=$(find ~/.pub-cache -name "FlutterLocalNotificationsPlugin.java" | grep -v mirror | head -n 1)
          if [ -n "$FLUTTER_LOCAL_NOTIFICATIONS_PATH" ]; then
            echo "Patching $FLUTTER_LOCAL_NOTIFICATIONS_PATH"
            sed -i 's/bigLargeIcon(null)/bigLargeIcon((android.graphics.Bitmap)null)/g' "$FLUTTER_LOCAL_NOTIFICATIONS_PATH"
            echo "✅ 已修复Flutter本地通知插件"
          else
            echo "⚠️ 未找到FlutterLocalNotificationsPlugin.java文件，跳过修复"
          fi
        
      - name: 检查资源目录
        run: |
          # 确保assets目录存在
          mkdir -p assets/images
          mkdir -p assets/i18n
          mkdir -p assets/sounds
          echo "已确保所有资源目录存在"
          
      - name: 分析代码
        run: flutter analyze
  
  build-android:
    name: 构建Android应用
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9 # v4.1.1
        with:
          fetch-depth: 0  # 获取完整历史用于版本号生成

      - name: 设置Java环境
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: 设置Flutter环境
        uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56 # v2.14.0
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true
      
      - name: 缓存Pub依赖
        uses: actions/cache@0769f2e44373d687c841be56f618397100943c5e # v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
          
      - name: 缓存Gradle
        uses: actions/cache@0769f2e44373d687c841be56f618397100943c5e # v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          
      - name: 获取依赖
        run: flutter pub get
      
      - name: 自动修复插件问题
        run: |
          FLUTTER_LOCAL_NOTIFICATIONS_PATH=$(find ~/.pub-cache -name "FlutterLocalNotificationsPlugin.java" | grep -v mirror | head -n 1)
          if [ -n "$FLUTTER_LOCAL_NOTIFICATIONS_PATH" ]; then
            echo "Patching $FLUTTER_LOCAL_NOTIFICATIONS_PATH"
            sed -i 's/bigLargeIcon(null)/bigLargeIcon((android.graphics.Bitmap)null)/g' "$FLUTTER_LOCAL_NOTIFICATIONS_PATH"
            echo "✅ 已修复Flutter本地通知插件"
          else
            echo "⚠️ 未找到FlutterLocalNotificationsPlugin.java文件，跳过修复"
          fi
        
      - name: 检查资源目录
        run: |
          # 确保assets目录存在
          mkdir -p assets/images
          mkdir -p assets/i18n
          mkdir -p assets/sounds
          echo "已确保所有资源目录存在"
        
      - name: 获取版本号
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          
          # 检查是否是标签触发的构建
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # 验证标签版本是否与pubspec.yaml中的版本匹配
            PUBSPEC_VERSION=$(echo "$VERSION" | sed 's/+.*//')
            if [ "$TAG_VERSION" != "$PUBSPEC_VERSION" ]; then
              echo "::warning::标签版本 $TAG_VERSION 与pubspec.yaml中的版本 $PUBSPEC_VERSION 不匹配!"
            fi
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
        
      - name: 构建APK
        run: |
          # 设置正确的JAVA_HOME环境变量，覆盖本地配置
          export JAVA_HOME=$JAVA_HOME_17_X64
          flutter build apk --release
        
      - name: 上传APK
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: scheduling-assistant-${{ steps.version.outputs.version }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
      
  build-ios:
    name: 构建iOS应用
    needs: analyze
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9 # v4.1.1
        with:
          fetch-depth: 0  # 获取完整历史用于版本号生成
        
      - name: 设置Flutter环境
        uses: subosito/flutter-action@1c5eb12d812966ca84680edc38353a0851c8fd56 # v2.14.0
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true
      
      - name: 缓存Pub依赖
        uses: actions/cache@0769f2e44373d687c841be56f618397100943c5e # v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
          
      - name: 获取依赖
        run: flutter pub get
      
      - name: 检查资源目录
        run: |
          # 确保assets目录存在
          mkdir -p assets/images
          mkdir -p assets/i18n
          mkdir -p assets/sounds
          echo "已确保所有资源目录存在"
      
      - name: 获取版本号
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        
      - name: 构建iOS
        run: |
          # 确保使用正确的Java路径
          export JAVA_HOME=$JAVA_HOME_17_X64
          flutter build ios --release --no-codesign
          
      - name: 创建IPA文件 (不包含签名)
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app-release-unsigned.ipa Payload
          
      - name: 上传IPA
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: scheduling-assistant-${{ steps.version.outputs.version }}.ipa
          path: build/ios/iphoneos/app-release-unsigned.ipa
          retention-days: 7
          
  create-release:
    name: 创建发布包
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9 # v4.1.1
        with:
          fetch-depth: 0  # 获取完整历史用于版本号生成
      
      - name: 获取版本号
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          PUBSPEC_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "pubspec_version=$PUBSPEC_VERSION" >> $GITHUB_OUTPUT
      
      - name: 下载Android APK
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.2
        with:
          name: scheduling-assistant-${{ steps.version.outputs.pubspec_version }}+*.apk
          path: ./artifacts
      
      - name: 下载iOS IPA
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.2
        with:
          name: scheduling-assistant-${{ steps.version.outputs.pubspec_version }}+*.ipa
          path: ./artifacts
      
      - name: 列出下载的文件
        run: ls -la ./artifacts
      
      - name: 生成变更日志
        id: changelog
        run: |
          # 尝试从CHANGELOG.md获取变更日志内容，若无则使用提交记录
          CHANGELOG=""
          VERSION=${{ steps.version.outputs.version }}
          
          if [ -f "CHANGELOG.md" ]; then
            # 尝试提取当前版本的变更日志
            CHANGELOG=$(awk -v ver="## [$VERSION]" '/^## \[/{flag=0} $0~ver{flag=1; next} flag{print}' CHANGELOG.md | sed '/^## \[/,$d')
          fi
          
          # 如果没有找到变更日志，则使用提交历史
          if [ -z "$CHANGELOG" ]; then
            echo "未找到版本变更日志，使用提交历史..."
            # 尝试找到上一个标签，如果没有则从头开始
            PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
            if [ -z "$PREV_TAG" ]; then
              echo "没有找到上一个标签，使用全部提交历史..."
              CHANGELOG=$(git log --pretty=format:"- %s" --no-merges -n 50)
            else
              CHANGELOG=$(git log --pretty=format:"- %s" --no-merges ${PREV_TAG}..HEAD)
            fi
          fi
          
          # 添加自动生成的更新时间和版本信息
          FINAL_CHANGELOG="## 排班助手 v$VERSION 发布说明\n\n**发布日期:** $(date +"%Y-%m-%d")\n\n### 更新内容\n\n$CHANGELOG\n\n### 安装说明\n- 点击下方APK下载安装\n- 如遇到安装问题，请卸载旧版本后重新安装"
          
          # 将变更日志内容保存到文件，以便下一步使用
          echo -e "$FINAL_CHANGELOG" > changelog.txt
          cat changelog.txt
      
      - name: 创建Release
        uses: softprops/action-gh-release@ab50eebb6488051c6788d97fa95232267c6a4e23 # v1
        with:
          name: 排班助手 v${{ steps.version.outputs.version }}
          body_path: changelog.txt
          files: |
            ./artifacts/app-release.apk
            ./artifacts/app-release-unsigned.ipa
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 